# Generated by Django 5.0.7 on 2024-08-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
    ]
